package com.github.badoualy.telegram.tl.api

import com.github.badoualy.telegram.tl.TLObjectUtils.SIZE_BOOLEAN
import com.github.badoualy.telegram.tl.TLObjectUtils.SIZE_CONSTRUCTOR_ID
import com.github.badoualy.telegram.tl.TLObjectUtils.SIZE_DOUBLE
import com.github.badoualy.telegram.tl.TLObjectUtils.SIZE_INT32
import com.github.badoualy.telegram.tl.TLObjectUtils.SIZE_INT64
import com.github.badoualy.telegram.tl.TLObjectUtils.computeTLBytesSerializedSize
import com.github.badoualy.telegram.tl.TLObjectUtils.computeTLStringSerializedSize
import com.github.badoualy.telegram.tl.core.TLObject

/**
 * Abstraction level for the following constructors:
 * * [updateAttachMenuBots#17b7a20b][TLUpdateAttachMenuBots]
 * * [updateAutoSaveSettings#ec05b097][TLUpdateAutoSaveSettings]
 * * [updateBotCallbackQuery#b9cfc48d][TLUpdateBotCallbackQuery]
 * * [updateBotChatBoost#904dd49c][TLUpdateBotChatBoost]
 * * [updateBotChatInviteRequester#11dfa986][TLUpdateBotChatInviteRequester]
 * * [updateBotCommands#4d712f2e][TLUpdateBotCommands]
 * * [updateBotInlineQuery#496f379c][TLUpdateBotInlineQuery]
 * * [updateBotInlineSend#12f12a07][TLUpdateBotInlineSend]
 * * [updateBotMenuButton#14b85813][TLUpdateBotMenuButton]
 * * [updateBotMessageReaction#ac21d3ce][TLUpdateBotMessageReaction]
 * * [updateBotMessageReactions#9cb7759][TLUpdateBotMessageReactions]
 * * [updateBotPrecheckoutQuery#8caa9a96][TLUpdateBotPrecheckoutQuery]
 * * [updateBotShippingQuery#b5aefd7d][TLUpdateBotShippingQuery]
 * * [updateBotStopped#c4870a49][TLUpdateBotStopped]
 * * [updateBotWebhookJSON#8317c0c3][TLUpdateBotWebhookJSON]
 * * [updateBotWebhookJSONQuery#9b9240a6][TLUpdateBotWebhookJSONQuery]
 * * [updateChannel#635b4c09][TLUpdateChannel]
 * * [updateChannelAvailableMessages#b23fc698][TLUpdateChannelAvailableMessages]
 * * [updateChannelMessageForwards#d29a27f4][TLUpdateChannelMessageForwards]
 * * [updateChannelMessageViews#f226ac08][TLUpdateChannelMessageViews]
 * * [updateChannelParticipant#985d3abb][TLUpdateChannelParticipant]
 * * [updateChannelPinnedTopic#192efbe3][TLUpdateChannelPinnedTopic]
 * * [updateChannelPinnedTopics#fe198602][TLUpdateChannelPinnedTopics]
 * * [updateChannelReadMessagesContents#ea29055d][TLUpdateChannelReadMessagesContents]
 * * [updateChannelTooLong#108d941f][TLUpdateChannelTooLong]
 * * [updateChannelUserTyping#8c88c923][TLUpdateChannelUserTyping]
 * * [updateChannelViewForumAsMessages#7b68920][TLUpdateChannelViewForumAsMessages]
 * * [updateChannelWebPage#2f2ba99f][TLUpdateChannelWebPage]
 * * [updateChat#f89a6a4e][TLUpdateChat]
 * * [updateChatDefaultBannedRights#54c01850][TLUpdateChatDefaultBannedRights]
 * * [updateChatParticipant#d087663a][TLUpdateChatParticipant]
 * * [updateChatParticipantAdd#3dda5451][TLUpdateChatParticipantAdd]
 * * [updateChatParticipantAdmin#d7ca61a2][TLUpdateChatParticipantAdmin]
 * * [updateChatParticipantDelete#e32f3d77][TLUpdateChatParticipantDelete]
 * * [updateChatParticipants#7761198][TLUpdateChatParticipants]
 * * [updateChatUserTyping#83487af0][TLUpdateChatUserTyping]
 * * [updateConfig#a229dd06][TLUpdateConfig]
 * * [updateContactsReset#7084a7be][TLUpdateContactsReset]
 * * [updateDcOptions#8e5e9873][TLUpdateDcOptions]
 * * [updateDeleteChannelMessages#c32d5b12][TLUpdateDeleteChannelMessages]
 * * [updateDeleteMessages#a20db0e5][TLUpdateDeleteMessages]
 * * [updateDeleteScheduledMessages#90866cee][TLUpdateDeleteScheduledMessages]
 * * [updateDialogFilter#26ffde7d][TLUpdateDialogFilter]
 * * [updateDialogFilterOrder#a5d72105][TLUpdateDialogFilterOrder]
 * * [updateDialogFilters#3504914f][TLUpdateDialogFilters]
 * * [updateDialogPinned#6e6fe51c][TLUpdateDialogPinned]
 * * [updateDialogUnreadMark#e16459c3][TLUpdateDialogUnreadMark]
 * * [updateDraftMessage#1b49ec6d][TLUpdateDraftMessage]
 * * [updateEditChannelMessage#1b3f4df7][TLUpdateEditChannelMessage]
 * * [updateEditMessage#e40370a3][TLUpdateEditMessage]
 * * [updateEncryptedChatTyping#1710f156][TLUpdateEncryptedChatTyping]
 * * [updateEncryptedMessagesRead#38fe25b7][TLUpdateEncryptedMessagesRead]
 * * [updateEncryption#b4a2e88d][TLUpdateEncryption]
 * * [updateFavedStickers#e511996d][TLUpdateFavedStickers]
 * * [updateFolderPeers#19360dc0][TLUpdateFolderPeers]
 * * [updateGeoLiveViewed#871fb939][TLUpdateGeoLiveViewed]
 * * [updateGroupCall#14b24500][TLUpdateGroupCall]
 * * [updateGroupCallConnection#b783982][TLUpdateGroupCallConnection]
 * * [updateGroupCallParticipants#f2ebdb4e][TLUpdateGroupCallParticipants]
 * * [updateGroupInvitePrivacyForbidden#ccf08ad6][TLUpdateGroupInvitePrivacyForbidden]
 * * [updateInlineBotCallbackQuery#691e9052][TLUpdateInlineBotCallbackQuery]
 * * [updateLangPack#56022f4d][TLUpdateLangPack]
 * * [updateLangPackTooLong#46560264][TLUpdateLangPackTooLong]
 * * [updateLoginToken#564fe691][TLUpdateLoginToken]
 * * [updateMessageExtendedMedia#5a73a98c][TLUpdateMessageExtendedMedia]
 * * [updateMessageID#4e90bfd6][TLUpdateMessageID]
 * * [updateMessagePoll#aca1657b][TLUpdateMessagePoll]
 * * [updateMessagePollVote#24f40e77][TLUpdateMessagePollVote]
 * * [updateMessageReactions#5e1b3cb8][TLUpdateMessageReactions]
 * * [updateMoveStickerSetToTop#86fccf85][TLUpdateMoveStickerSetToTop]
 * * [updateNewAuthorization#8951abef][TLUpdateNewAuthorization]
 * * [updateNewChannelMessage#62ba04d9][TLUpdateNewChannelMessage]
 * * [updateNewEncryptedMessage#12bcbd9a][TLUpdateNewEncryptedMessage]
 * * [updateNewMessage#1f2b0afd][TLUpdateNewMessage]
 * * [updateNewScheduledMessage#39a51dfb][TLUpdateNewScheduledMessage]
 * * [updateNewStickerSet#688a30aa][TLUpdateNewStickerSet]
 * * [updateNotifySettings#bec268ef][TLUpdateNotifySettings]
 * * [updatePeerBlocked#ebe07752][TLUpdatePeerBlocked]
 * * [updatePeerHistoryTTL#bb9bb9a5][TLUpdatePeerHistoryTTL]
 * * [updatePeerLocated#b4afcfb0][TLUpdatePeerLocated]
 * * [updatePeerSettings#6a7e7366][TLUpdatePeerSettings]
 * * [updatePeerWallpaper#ae3f101d][TLUpdatePeerWallpaper]
 * * [updatePendingJoinRequests#7063c3db][TLUpdatePendingJoinRequests]
 * * [updatePhoneCall#ab0f6b1e][TLUpdatePhoneCall]
 * * [updatePhoneCallSignalingData#2661bf09][TLUpdatePhoneCallSignalingData]
 * * [updatePinnedChannelMessages#5bb98608][TLUpdatePinnedChannelMessages]
 * * [updatePinnedDialogs#fa0f3ca2][TLUpdatePinnedDialogs]
 * * [updatePinnedMessages#ed85eab5][TLUpdatePinnedMessages]
 * * [updatePinnedSavedDialogs#686c85a6][TLUpdatePinnedSavedDialogs]
 * * [updatePrivacy#ee3b272a][TLUpdatePrivacy]
 * * [updatePtsChanged#3354678f][TLUpdatePtsChanged]
 * * [updateReadChannelDiscussionInbox#d6b19546][TLUpdateReadChannelDiscussionInbox]
 * * [updateReadChannelDiscussionOutbox#695c9e7c][TLUpdateReadChannelDiscussionOutbox]
 * * [updateReadChannelInbox#922e6e10][TLUpdateReadChannelInbox]
 * * [updateReadChannelOutbox#b75f99a9][TLUpdateReadChannelOutbox]
 * * [updateReadFeaturedEmojiStickers#fb4c496c][TLUpdateReadFeaturedEmojiStickers]
 * * [updateReadFeaturedStickers#571d2742][TLUpdateReadFeaturedStickers]
 * * [updateReadHistoryInbox#9c974fdf][TLUpdateReadHistoryInbox]
 * * [updateReadHistoryOutbox#2f2f21bf][TLUpdateReadHistoryOutbox]
 * * [updateReadMessagesContents#f8227181][TLUpdateReadMessagesContents]
 * * [updateReadStories#f74e932b][TLUpdateReadStories]
 * * [updateRecentEmojiStatuses#30f443db][TLUpdateRecentEmojiStatuses]
 * * [updateRecentReactions#6f7863f4][TLUpdateRecentReactions]
 * * [updateRecentStickers#9a422c20][TLUpdateRecentStickers]
 * * [updateSavedDialogPinned#aeaf9e74][TLUpdateSavedDialogPinned]
 * * [updateSavedGifs#9375341e][TLUpdateSavedGifs]
 * * [updateSavedRingtones#74d8be99][TLUpdateSavedRingtones]
 * * [updateSentStoryReaction#7d627683][TLUpdateSentStoryReaction]
 * * [updateServiceNotification#ebe46819][TLUpdateServiceNotification]
 * * [updateStickerSets#31c24808][TLUpdateStickerSets]
 * * [updateStickerSetsOrder#bb2d201][TLUpdateStickerSetsOrder]
 * * [updateStoriesStealthMode#2c084dc1][TLUpdateStoriesStealthMode]
 * * [updateStory#75b3b798][TLUpdateStory]
 * * [updateStoryID#1bf335b9][TLUpdateStoryID]
 * * [updateTheme#8216fba3][TLUpdateTheme]
 * * [updateTranscribedAudio#84cd5a][TLUpdateTranscribedAudio]
 * * [updateUser#20529438][TLUpdateUser]
 * * [updateUserEmojiStatus#28373599][TLUpdateUserEmojiStatus]
 * * [updateUserName#a7848924][TLUpdateUserName]
 * * [updateUserPhone#5492a13][TLUpdateUserPhone]
 * * [updateUserStatus#e5bdf8de][TLUpdateUserStatus]
 * * [updateUserTyping#c01e857f][TLUpdateUserTyping]
 * * [updateWebPage#7f891213][TLUpdateWebPage]
 * * [updateWebViewResultSent#1592b79d][TLUpdateWebViewResultSent]
 *
 * @author Yannick Badoual yann.badoual@gmail.com
 * @see <a href="http://github.com/badoualy/kotlogram">http://github.com/badoualy/kotlogram</a>
 */
abstract class TLAbsUpdate : TLObject()
