package com.github.badoualy.telegram.tl.api

import com.github.badoualy.telegram.tl.core.TLObject

/**
 * Abstraction level for the following constructors:
 * * [updateBotCallbackQuery#b9cfc48d][TLUpdateBotCallbackQuery]
 * * [updateBotCommands#4d712f2e][TLUpdateBotCommands]
 * * [updateBotInlineQuery#496f379c][TLUpdateBotInlineQuery]
 * * [updateBotInlineSend#12f12a07][TLUpdateBotInlineSend]
 * * [updateBotPrecheckoutQuery#8caa9a96][TLUpdateBotPrecheckoutQuery]
 * * [updateBotShippingQuery#b5aefd7d][TLUpdateBotShippingQuery]
 * * [updateBotStopped#c4870a49][TLUpdateBotStopped]
 * * [updateBotWebhookJSON#8317c0c3][TLUpdateBotWebhookJSON]
 * * [updateBotWebhookJSONQuery#9b9240a6][TLUpdateBotWebhookJSONQuery]
 * * [updateChannel#635b4c09][TLUpdateChannel]
 * * [updateChannelAvailableMessages#b23fc698][TLUpdateChannelAvailableMessages]
 * * [updateChannelMessageForwards#d29a27f4][TLUpdateChannelMessageForwards]
 * * [updateChannelMessageViews#f226ac08][TLUpdateChannelMessageViews]
 * * [updateChannelParticipant#985d3abb][TLUpdateChannelParticipant]
 * * [updateChannelReadMessagesContents#44bdd535][TLUpdateChannelReadMessagesContents]
 * * [updateChannelTooLong#108d941f][TLUpdateChannelTooLong]
 * * [updateChannelUserTyping#8c88c923][TLUpdateChannelUserTyping]
 * * [updateChannelWebPage#2f2ba99f][TLUpdateChannelWebPage]
 * * [updateChat#f89a6a4e][TLUpdateChat]
 * * [updateChatDefaultBannedRights#54c01850][TLUpdateChatDefaultBannedRights]
 * * [updateChatParticipant#d087663a][TLUpdateChatParticipant]
 * * [updateChatParticipantAdd#3dda5451][TLUpdateChatParticipantAdd]
 * * [updateChatParticipantAdmin#d7ca61a2][TLUpdateChatParticipantAdmin]
 * * [updateChatParticipantDelete#e32f3d77][TLUpdateChatParticipantDelete]
 * * [updateChatParticipants#7761198][TLUpdateChatParticipants]
 * * [updateChatUserTyping#83487af0][TLUpdateChatUserTyping]
 * * [updateConfig#a229dd06][TLUpdateConfig]
 * * [updateContactsReset#7084a7be][TLUpdateContactsReset]
 * * [updateDcOptions#8e5e9873][TLUpdateDcOptions]
 * * [updateDeleteChannelMessages#c32d5b12][TLUpdateDeleteChannelMessages]
 * * [updateDeleteMessages#a20db0e5][TLUpdateDeleteMessages]
 * * [updateDeleteScheduledMessages#90866cee][TLUpdateDeleteScheduledMessages]
 * * [updateDialogFilter#26ffde7d][TLUpdateDialogFilter]
 * * [updateDialogFilterOrder#a5d72105][TLUpdateDialogFilterOrder]
 * * [updateDialogFilters#3504914f][TLUpdateDialogFilters]
 * * [updateDialogPinned#6e6fe51c][TLUpdateDialogPinned]
 * * [updateDialogUnreadMark#e16459c3][TLUpdateDialogUnreadMark]
 * * [updateDraftMessage#ee2bb969][TLUpdateDraftMessage]
 * * [updateEditChannelMessage#1b3f4df7][TLUpdateEditChannelMessage]
 * * [updateEditMessage#e40370a3][TLUpdateEditMessage]
 * * [updateEncryptedChatTyping#1710f156][TLUpdateEncryptedChatTyping]
 * * [updateEncryptedMessagesRead#38fe25b7][TLUpdateEncryptedMessagesRead]
 * * [updateEncryption#b4a2e88d][TLUpdateEncryption]
 * * [updateFavedStickers#e511996d][TLUpdateFavedStickers]
 * * [updateFolderPeers#19360dc0][TLUpdateFolderPeers]
 * * [updateGeoLiveViewed#871fb939][TLUpdateGeoLiveViewed]
 * * [updateGroupCall#14b24500][TLUpdateGroupCall]
 * * [updateGroupCallConnection#b783982][TLUpdateGroupCallConnection]
 * * [updateGroupCallParticipants#f2ebdb4e][TLUpdateGroupCallParticipants]
 * * [updateInlineBotCallbackQuery#691e9052][TLUpdateInlineBotCallbackQuery]
 * * [updateLangPack#56022f4d][TLUpdateLangPack]
 * * [updateLangPackTooLong#46560264][TLUpdateLangPackTooLong]
 * * [updateLoginToken#564fe691][TLUpdateLoginToken]
 * * [updateMessageID#4e90bfd6][TLUpdateMessageID]
 * * [updateMessagePoll#aca1657b][TLUpdateMessagePoll]
 * * [updateMessagePollVote#106395c9][TLUpdateMessagePollVote]
 * * [updateNewChannelMessage#62ba04d9][TLUpdateNewChannelMessage]
 * * [updateNewEncryptedMessage#12bcbd9a][TLUpdateNewEncryptedMessage]
 * * [updateNewMessage#1f2b0afd][TLUpdateNewMessage]
 * * [updateNewScheduledMessage#39a51dfb][TLUpdateNewScheduledMessage]
 * * [updateNewStickerSet#688a30aa][TLUpdateNewStickerSet]
 * * [updateNotifySettings#bec268ef][TLUpdateNotifySettings]
 * * [updatePeerBlocked#246a4b22][TLUpdatePeerBlocked]
 * * [updatePeerHistoryTTL#bb9bb9a5][TLUpdatePeerHistoryTTL]
 * * [updatePeerLocated#b4afcfb0][TLUpdatePeerLocated]
 * * [updatePeerSettings#6a7e7366][TLUpdatePeerSettings]
 * * [updatePhoneCall#ab0f6b1e][TLUpdatePhoneCall]
 * * [updatePhoneCallSignalingData#2661bf09][TLUpdatePhoneCallSignalingData]
 * * [updatePinnedChannelMessages#5bb98608][TLUpdatePinnedChannelMessages]
 * * [updatePinnedDialogs#fa0f3ca2][TLUpdatePinnedDialogs]
 * * [updatePinnedMessages#ed85eab5][TLUpdatePinnedMessages]
 * * [updatePrivacy#ee3b272a][TLUpdatePrivacy]
 * * [updatePtsChanged#3354678f][TLUpdatePtsChanged]
 * * [updateReadChannelDiscussionInbox#d6b19546][TLUpdateReadChannelDiscussionInbox]
 * * [updateReadChannelDiscussionOutbox#695c9e7c][TLUpdateReadChannelDiscussionOutbox]
 * * [updateReadChannelInbox#922e6e10][TLUpdateReadChannelInbox]
 * * [updateReadChannelOutbox#b75f99a9][TLUpdateReadChannelOutbox]
 * * [updateReadFeaturedStickers#571d2742][TLUpdateReadFeaturedStickers]
 * * [updateReadHistoryInbox#9c974fdf][TLUpdateReadHistoryInbox]
 * * [updateReadHistoryOutbox#2f2f21bf][TLUpdateReadHistoryOutbox]
 * * [updateReadMessagesContents#68c13933][TLUpdateReadMessagesContents]
 * * [updateRecentStickers#9a422c20][TLUpdateRecentStickers]
 * * [updateSavedGifs#9375341e][TLUpdateSavedGifs]
 * * [updateServiceNotification#ebe46819][TLUpdateServiceNotification]
 * * [updateStickerSets#43ae3dec][TLUpdateStickerSets]
 * * [updateStickerSetsOrder#bb2d201][TLUpdateStickerSetsOrder]
 * * [updateTheme#8216fba3][TLUpdateTheme]
 * * [updateUserName#c3f202e0][TLUpdateUserName]
 * * [updateUserPhone#5492a13][TLUpdateUserPhone]
 * * [updateUserPhoto#f227868c][TLUpdateUserPhoto]
 * * [updateUserStatus#e5bdf8de][TLUpdateUserStatus]
 * * [updateUserTyping#c01e857f][TLUpdateUserTyping]
 * * [updateWebPage#7f891213][TLUpdateWebPage]
 *
 * @author Yannick Badoual yann.badoual@gmail.com
 * @see <a href="http://github.com/badoualy/kotlogram">http://github.com/badoualy/kotlogram</a>
 */
abstract class TLAbsUpdate : TLObject()
